version: "3.9"

services: 
  mongo:
    image: mongo:6.0.19
    container_name: mongo
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/init_mongo.sh:/docker-entrypoint-initdb.d/init_mongo.sh
    ports:
      - "27017:27017"
    command: bash -c "docker-entrypoint.sh mongod --bind_ip_all --nojournal & mongoimport -d agile_data_science -c origin_dest_distances --file /data/db/origin_dest_distances.jsonl && wait"
    tty: true
  

  cassandra:
    image: bitnami/cassandra:latest
    container_name: cassandra
    volumes:
      - ./cassandra/create_keyspace.cql:/docker-entrypoint-initdb.d/create_keyspace.cql
    ports: 
      - "9042:9042"
    environment:
      - CASSANDRA_PORT=9042
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
    tty: true


  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    tty: true
      
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      - "KAFKA_LISTENERS=PLAINTEXT://kafka:9092"
      - "KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092"
      - "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181"
      - "KAFKA_CREATE_TOPICS=flight_delay_classification_request:1:1"
    depends_on:
      - zookeeper
    tty: true

  spark-master:
    build: ./spark
    container_name: spark-master
    ports:
      - "7077:7077"
    links:
      - 'mongo'
    depends_on:
      - 'mongo'
      - 'cassandra'
      - 'kafka'
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_MASTER_HOST=spark-master"
      - "INIT_DAEMON_STEP=setup_spark"
      - "constraint:node==spark-master"
    tty: true

  spark-worker-1:
    build: ./spark
    container_name: spark-worker-1
    depends_on:
      - mongo
      - kafka
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "INIT_DAEMON_STEP=setup_spark"
      - "constraint:node==spark-worker"
    tty: true

  
  spark-worker-2:
    build: ./spark
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - mongo
      - kafka
      - spark-master
    ports:
      - "8382:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==spark-worker"
    tty: true


  spark-submit:
    build: ./spark
    container_name: spark-submit
    depends_on:
      - mongo
      - kafka
      - spark-master
      - spark-worker-1
      - spark-worker-2
    ports:
      - "4040:4040"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==spark-master"
    command: /opt/spark/bin/spark-submit --deploy-mode client --class es.upm.dit.ging.predictor.MakePrediction --master spark://spark-master:7077  --packages org.mongodb.spark:mongo-spark-connector_2.12:10.1.1,org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.0,com.datastax.spark:spark-cassandra-connector_2.12:3.3.0 /home/practica_creativa_bdfi/flight_prediction/target/scala-2.12/flight_prediction_2.12-0.1.jar
    tty: true

  flask:
    build: ./flask
    container_name: flask
    ports:
      - "5001:5001"
    depends_on:
      - mongo
      - spark-master
      - kafka
      - spark-worker-1
      - spark-worker-2
      - spark-submit
    tty: true