version: "3.9"

services: 
  mongo:
    container_name: mongo
    image: mongo:6.0.19
    volumes:
      - ./mongodb/data:/data/db
      - ./mongodb/init_mongo.js:/docker-entrypoint-initdb.d/init_mongo.js
    #command: bash -c "docker-entrypoint.sh mongod --bind_ip_all --nojournal & mongoimport -d agile_data_science -c origin_dest_distances --file /data/db/origin_dest_distances.jsonl && wait"
    ports:
      - "27017:27017"
    tty: true

  zookeeper: 
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    tty: true

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    user: root
    ports:
      - "9092:9092"
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS="flight_delay_classification_request:1:1"
      - KAFKA_CREATE_TOPICS="flight_delay_classification_response:1:1"
    depends_on:
      - zookeeper
    tty: true

  spark:
    build: ./spark
    container_name: spark
    ports:
      - "7077:7077"
    links:
      - 'mongo'
    depends_on:
      - 'mongo'
      - 'kafka'
    command: bash -c "sleep 15; /opt/spark/bin/spark-submit --class es.upm.dit.ging.predictor.MakePrediction --master 'local[*]' --packages org.mongodb.spark:mongo-spark-connector_2.12:10.1.1,org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.0 target/scala-2.12/flight_prediction_2.12-0.1.jar"
    tty: true

  flask:
    container_name: flask
    build: ./flask
    depends_on:
      - spark
      - mongo
    ports:
      - "5001:5001"
    tty: true
volumes:
  mongodb: